# Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
# Project developers.  See the top-level LICENSE file for dates and other
# details.  No copyright assignment is required to contribute to VisIt.

###############################################################################
# VisIt Azure CI Checks
###############################################################################
# Azure Commands Ref:
# https://aka.ms/yaml

#####
# TO USE A NEW CONTAINER, UPDATE TAG NAME HERE AS PART OF YOUR PR!
#####
variables:
  container_tag: visitdav/visit-ci-develop:2020-08-24-shac49c21

# only build merge target pr to develop
trigger: none
pr:
  branches:
    include:
    - develop

# add fast fail checks here
stages:
- stage: Quick
  jobs:
  - job: Fast_Check
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        clean: boolean
        submodules: recursive

      - script: |
          #######################################
          # run our quick check
          #######################################
          echo "OK"
          # NOTE FOR AZURE: 
          # only return code of the command is checked!
        displayName: 'Example Fast Check'

# main checks build using docker containers that
# include tpls built with build_visit
- stage: Main
  jobs:
  - job: Main_Build
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 0
    container: ${{ variables.container_tag }}
    variables:
      TPLS_PATH: /masonry/build-mb-develop-ci-smoke/thirdparty_shared/third_party/
      CMAKE_VERSION: 3.9.3
    steps:
      - checkout: self
        clean: boolean
        submodules: recursive

      - script: |
           #################################
           # configure
           #################################
           # setup path to cmake
           export PATH=$PATH:${TPLS_PATH}/cmake/${CMAKE_VERSION}/ci/bin/
           # make dir for build
           mkdir build
           cd build
           # configure with cmake
           cmake -DVISIT_CONFIG_SITE:PATH="/visit-ci-cfg.cmake" ../src
        displayName: 'Configure with CMake'

      - script: |
           #################################
           # build
           #################################
           # build
           cd build
           make -j 4
        displayName: 'Build'

      - script: |
           #################################
           # test
           #################################
           # fetch subset of test data for smoke check
           # must get silo data since test suite
           # script first checks to make sure it exists
           git lfs pull --include silo_hdf5_test_data.7z
           git lfs pull --include vtk_test_data.7z
           cd build/testdata
           # unzip
           p7zip -d ../../data/silo_hdf5_test_data.7z
           p7zip -d ../../data/vtk_test_data.7z
           cd ../test
           ./run_visit_test_suite.sh  -v ../../src/test/tests/databases/vtk.py
        displayName: 'Test'
